// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5KOCNeE3Sc9ctWGA1G4gFObHPc1HT82E',
    appId: '1:513887187575:web:cca695dedea3227b084c72',
    messagingSenderId: '513887187575',
    projectId: 'alquran-a2de8',
    authDomain: 'alquran-a2de8.firebaseapp.com',
    storageBucket: 'alquran-a2de8.appspot.com',
    measurementId: 'G-N0RP99TS9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEf9sQth32bizHF9C9VJWBL2VYowP676Y',
    appId: '1:513887187575:android:b2bfdc41d475c5ef084c72',
    messagingSenderId: '513887187575',
    projectId: 'alquran-a2de8',
    storageBucket: 'alquran-a2de8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCREqUkUbA4AY7dEhlnEb8BYiOwxWeLKC8',
    appId: '1:513887187575:ios:1e2ab2f7d4a2a2da084c72',
    messagingSenderId: '513887187575',
    projectId: 'alquran-a2de8',
    storageBucket: 'alquran-a2de8.appspot.com',
    iosBundleId: 'com.example.alquran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCREqUkUbA4AY7dEhlnEb8BYiOwxWeLKC8',
    appId: '1:513887187575:ios:0b7ebcd4043b2d81084c72',
    messagingSenderId: '513887187575',
    projectId: 'alquran-a2de8',
    storageBucket: 'alquran-a2de8.appspot.com',
    iosBundleId: 'com.example.alquran.RunnerTests',
  );
}
